# vim:ft=kitty
## name: Ember
## author: Hossam Saraya
## license: MIT
## upstream: https://github.com/ember-theme/kitty

#: The basic colors

foreground                      #d8d0c0
background                      #242320
selection_foreground            #242320
selection_background            #d8d0c0


#: Cursor colors

cursor                          #e08060
cursor_text_color               #242320


#: URL underline color when hovering with mouse

url_color                       #e08060


#: kitty window border colors and terminal bell colors

active_border_color             #e08060
inactive_border_color           #3a3630
bell_border_color               #b07878
# visual_bell_color               none


#: OS Window titlebar colors

# wayland_titlebar_color          system
# macos_titlebar_color            system


#: Tab bar colors

active_tab_foreground           #242320
active_tab_background           #e08060
inactive_tab_foreground         #7a7468
inactive_tab_background         #3a3630
tab_bar_background              #242320
# tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

# mark1_foreground black
# mark1_background #98d3cb
# mark2_foreground black
# mark2_background #f2dcd3
# mark3_foreground black
# mark3_background #f274bc


#: The basic 16 colors

#: black
color0 #2a2826
color8 #4a4640

#: red
color1 #b07878
color9 #c08888

#: green
color2  #8a9868
color10 #9aaa78

#: yellow
color3  #c8b468
color11 #d8c478

#: blue
color4  #7890a0
color12 #88a0b0

#: magenta
color5  #988090
color13 #a890a0

#: cyan
color6  #80a090
color14 #90b0a0

#: white
color7  #d8d0c0
color15 #e8e0d0
