# vim:ft=kitty
## name: Gruvbox Material Dark Medium
## author: sainnhe
## license: MIT
## upstream: https://github.com/sainnhe/gruvbox-material

#: The basic colors

foreground                      #d4be98
background                      #282828
selection_foreground            #282828
selection_background            #d4be98


#: Cursor colors

cursor                          #d4be98
cursor_text_color               #282828


#: URL underline color when hovering with mouse

url_color                       #7daea3


#: kitty window border colors and terminal bell colors

active_border_color             #a9b665
inactive_border_color           #32302f
bell_border_color               #ea6962


#: Tab bar colors

active_tab_foreground           #282828
active_tab_background           #a9b665
inactive_tab_foreground         #928374
inactive_tab_background         #32302f
tab_bar_background              #282828


#: The basic 16 colors

#: black
color0 #665c54
color8 #928374

#: red
color1 #ea6962
color9 #ea6962

#: green
color2  #a9b665
color10 #a9b665

#: yellow
color3  #d8a657
color11 #e78a4e

#: blue
color4  #7daea3
color12 #7daea3

#: magenta
color5  #d3869b
color13 #d3869b

#: cyan
color6  #89b482
color14 #89b482

#: white
color7  #d4be98
color15 #ddc7a1
