font_size 12
inactive_text_alpha 0.5
macos_option_as_alt yes
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
hide_window_decorations titlebar-only
window_padding_width 5
window_margin_width 0
window_border_width 1.5pt
enabled_layouts splits,stack
tab_title_template "{fmt.fg.color3}({index}){fmt.fg.tab} {title}{' [Z]' if layout_name == 'stack' else ''}"
active_tab_title_template "({index}) {title}{' [Z]' if layout_name == 'stack' else ''}"
cursor_trail 1
scrollback_lines 10000
scrollback_pager_history_size 4
mouse_hide_wait -1
show_hyperlink_targets yes
strip_trailing_spaces smart

scrollbar scrolled

map cmd+f combine : show_scrollback : send_text normal,application /

map cmd+enter no_op
map cmd+shift+s launch --cwd=current --location=hsplit
map cmd+shift+v launch --cwd=current --location=vsplit
map cmd+w close_window
map ctrl+shift+a detach_window ask
map cmd+shift+z toggle_layout stack
map cmd+shift+r set_tab_title " "

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right

# Unset the mapping to pass the keys to neovim
map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+l

# the 3 here is the resize amount, adjust as needed
map ctrl+shift+j kitten relative_resize.py down  3 
map ctrl+shift+k kitten relative_resize.py up    3
map ctrl+shift+h kitten relative_resize.py left  3
map ctrl+shift+l kitten relative_resize.py right 3

# Unset the mapping to pass the keys to neovim
map --when-focus-on var:IS_NVIM ctrl+shift+j
map --when-focus-on var:IS_NVIM ctrl+shift+k
map --when-focus-on var:IS_NVIM ctrl+shift+h
map --when-focus-on var:IS_NVIM ctrl+shift+l

map ctrl+shift+alt+j move_window down
map ctrl+shift+alt+k move_window up
map ctrl+shift+alt+h move_window left
map ctrl+shift+alt+l move_window right

# Unset the mapping to pass the keys to neovim
map --when-focus-on var:IS_NVIM ctrl+shift+alt+j
map --when-focus-on var:IS_NVIM ctrl+shift+alt+k
map --when-focus-on var:IS_NVIM ctrl+shift+alt+h
map --when-focus-on var:IS_NVIM ctrl+shift+alt+l

mouse_map left click ungrabbed no-op
mouse_map cmd+left click ungrabbed mouse_handle_click link

allow_remote_control socket-only
listen_on unix:/tmp/mykitty
shell_integration enabled

# BEGIN_KITTY_THEME
include nordfox.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family='JetBrains Mono' variable_name=JetBrainsMono style=Regular
bold_font        family='JetBrains Mono' style=ExtraBold variable_name=JetBrainsMono
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
