format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

right_format = """
$cmd_duration\
"""
command_timeout = 3600

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 0

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "green"

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)]($style) ($ahead_behind$stashed)]($style) "
style = "yellow"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "yellow"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

